#!/bin/bash

# we get revision info on stdin
while read oldrev newrev refname
do
    branch=$(git describe --contains --all $refname)
    echo "pushing branch $branch"
done

RAILS_ROOT=/var/www/lrweb
VBIN=$RAILS_ROOT/vendor/bin
export RAILS_ENV=production

git checkout -q -f $branch

revn=$(git rev-parse --short $branch)
echo $branch-$revn > $RAILS_ROOT/REVISION

cd $RAILS_ROOT

if [ -f  "/usr/local/rvm/scripts/rvm" ]; then
  source /usr/local/rvm/scripts/rvm
  rvm use `cat .ruby-version`
fi

bundle check || bundle install --binstubs $VBIN --local --deployment --without development test

echo "rake db:migrate"
$VBIN/rake db:migrate

# NOTE jammit will fail if this is not writable by current user
mkdir -p public/assets
echo "processing assets with jammit"
$VBIN/jammit

mkdir -p tmp
touch $RAILS_ROOT/tmp/restart.txt
